data:
  sample_sheet: samples.csv
  # Library can be PE or SE
  library: PE

aligner:
  tool: bwa
  aln_flags: ""

sam:
  sam_flags: ""

vcf:
  pileup_flags: -d 100
  call_flags: --ploidy 2
  # Call type can be multi-sample or sample-vcf
  call_type: multi-sample

# Run time parameters
genome: refs/genome.fa
ref_dir: refs
idx_dir: refs/idx
aln_dir: bam
vcf_dir: vcf
ncpu: 4
